-- MySQL Script generated by MySQL Workbench
-- Sat 18 Mar 2023 02:30:28 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grupo25
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grupo25` ;

-- -----------------------------------------------------
-- Schema grupo25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo25` DEFAULT CHARACTER SET utf8 ;
USE `grupo25` ;

-- -----------------------------------------------------
-- Table `grupo25`.`ESTADO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`ESTADO_CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `estado_UNIQUE` ON `grupo25`.`ESTADO_CLIENTE` (`ESTADO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`DIRECCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CIUDAD` VARCHAR(45) NOT NULL,
  `CODIGO_POSTAL` VARCHAR(45) NOT NULL,
  `PAIS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo25`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`EMPRESA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CIERRE` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo25`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`PERSONA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(45) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(45) NULL,
  `FECHA_NACIMIENTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `DNI_UNIQUE` ON `grupo25`.`PERSONA` (`DNI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`ROL_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`ROL_PERSONA` (
  `ID` INT NOT NULL,
  `PERSONA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_RolPersona_Persona1`
    FOREIGN KEY (`PERSONA`)
    REFERENCES `grupo25`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RolPersona_Persona1_idx` ON `grupo25`.`ROL_PERSONA` (`PERSONA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO_CLIENTE` INT NOT NULL,
  `DIRECCION` INT NOT NULL,
  `USUARIO` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `FECHA_INICIO` DATE NOT NULL,
  `EMPRESA` INT NULL,
  `ROL_PERSONA` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Cliente_EstadoCliente1`
    FOREIGN KEY (`ESTADO_CLIENTE`)
    REFERENCES `grupo25`.`ESTADO_CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Direccion1`
    FOREIGN KEY (`DIRECCION`)
    REFERENCES `grupo25`.`DIRECCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Empresa1`
    FOREIGN KEY (`EMPRESA`)
    REFERENCES `grupo25`.`EMPRESA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_RolPersona1`
    FOREIGN KEY (`ROL_PERSONA`)
    REFERENCES `grupo25`.`ROL_PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_EstadoCliente1_idx` ON `grupo25`.`CLIENTE` (`ESTADO_CLIENTE` ASC) VISIBLE;

CREATE INDEX `fk_Cliente_Direccion1_idx` ON `grupo25`.`CLIENTE` (`DIRECCION` ASC) VISIBLE;

CREATE INDEX `fk_Cliente_Empresa1_idx` ON `grupo25`.`CLIENTE` (`EMPRESA` ASC) VISIBLE;

CREATE INDEX `fk_Cliente_RolPersona1_idx` ON `grupo25`.`CLIENTE` (`ROL_PERSONA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`ESTADO_CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`ESTADO_CUENTA` (
  `ID` INT NOT NULL,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo25`.`CUENTA_BANCARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CUENTA_BANCARIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IBAN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iban_UNIQUE` ON `grupo25`.`CUENTA_BANCARIA` (`IBAN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`CUENTA_INTERNA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CUENTA_INTERNA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUENTA_BANCARIA` INT NOT NULL,
  `PROPIETARIO` INT NOT NULL,
  `MONEDA` VARCHAR(45) NOT NULL,
  `PAIS` VARCHAR(45) NOT NULL,
  `CANTIDAD` DOUBLE NOT NULL,
  `ESTADO_CUENTA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_CuentaBanco_Cliente1`
    FOREIGN KEY (`PROPIETARIO`)
    REFERENCES `grupo25`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaBanco_EstadoCuenta1`
    FOREIGN KEY (`ESTADO_CUENTA`)
    REFERENCES `grupo25`.`ESTADO_CUENTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaInterna_CuentaBancaria1`
    FOREIGN KEY (`CUENTA_BANCARIA`)
    REFERENCES `grupo25`.`CUENTA_BANCARIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CuentaBanco_Cliente1_idx` ON `grupo25`.`CUENTA_INTERNA` (`PROPIETARIO` ASC) VISIBLE;

CREATE INDEX `fk_CuentaBanco_EstadoCuenta1_idx` ON `grupo25`.`CUENTA_INTERNA` (`ESTADO_CUENTA` ASC) VISIBLE;

CREATE INDEX `fk_CuentaInterna_CuentaBancaria1_idx` ON `grupo25`.`CUENTA_INTERNA` (`CUENTA_BANCARIA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`TRANSACCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`TRANSACCION` (
  `ID` INT NOT NULL,
  `FECHA_INSTRUCCION` DATE NULL,
  `FECHA_EJECUCION` DATE NULL,
  `CUENTA_ORIGEN` INT NOT NULL,
  `CUENTA_DESTINO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Transaccion_CuentaBancaria1`
    FOREIGN KEY (`CUENTA_ORIGEN`)
    REFERENCES `grupo25`.`CUENTA_BANCARIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_CuentaBancaria2`
    FOREIGN KEY (`CUENTA_DESTINO`)
    REFERENCES `grupo25`.`CUENTA_BANCARIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Transaccion_CuentaBancaria1_idx` ON `grupo25`.`TRANSACCION` (`CUENTA_ORIGEN` ASC) VISIBLE;

CREATE INDEX `fk_Transaccion_CuentaBancaria2_idx` ON `grupo25`.`TRANSACCION` (`CUENTA_DESTINO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`CAMBIO_DIVISA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CAMBIO_DIVISA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TRANSACCION` INT NOT NULL,
  `MONEDA_VENTA` VARCHAR(45) NOT NULL,
  `MONEDA_COMPRA` VARCHAR(45) NOT NULL,
  `TIPO_CAMBIO` VARCHAR(45) NOT NULL,
  `CANTIDAD_COMPRA` VARCHAR(45) NOT NULL,
  `CANTIDAD_VENTA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_CambioDivisa_Transaccion1`
    FOREIGN KEY (`TRANSACCION`)
    REFERENCES `grupo25`.`TRANSACCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CambioDivisa_Transaccion1_idx` ON `grupo25`.`CAMBIO_DIVISA` (`TRANSACCION` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`PAGO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TRANSACCION` INT NOT NULL,
  `CAMBIO_DIVISA` INT NULL,
  `MONEDA` VARCHAR(45) NOT NULL,
  `CANTIDAD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Pago_Transaccion1`
    FOREIGN KEY (`TRANSACCION`)
    REFERENCES `grupo25`.`TRANSACCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_CambioDivisa1`
    FOREIGN KEY (`CAMBIO_DIVISA`)
    REFERENCES `grupo25`.`CAMBIO_DIVISA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_CambioDivisa1_idx` ON `grupo25`.`PAGO` (`CAMBIO_DIVISA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`SOCIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`SOCIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_PERSONA` INT NOT NULL,
  `EMPRESA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Socio_RolPersona1`
    FOREIGN KEY (`ROL_PERSONA`)
    REFERENCES `grupo25`.`ROL_PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Socio_Empresa1`
    FOREIGN KEY (`EMPRESA`)
    REFERENCES `grupo25`.`EMPRESA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Socio_RolPersona1_idx` ON `grupo25`.`SOCIO` (`ROL_PERSONA` ASC) VISIBLE;

CREATE INDEX `fk_Socio_Empresa1_idx` ON `grupo25`.`SOCIO` (`EMPRESA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`GESTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`GESTOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_PERSONA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Gestor_RolPersona1`
    FOREIGN KEY (`ROL_PERSONA`)
    REFERENCES `grupo25`.`ROL_PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gestor_RolPersona1_idx` ON `grupo25`.`GESTOR` (`ROL_PERSONA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`ASISTENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`ASISTENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_PERSONA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Asistente_RolPersona1`
    FOREIGN KEY (`ROL_PERSONA`)
    REFERENCES `grupo25`.`ROL_PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Asistente_RolPersona1_idx` ON `grupo25`.`ASISTENTE` (`ROL_PERSONA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CHAT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE` INT NOT NULL,
  `ASISTENTE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Chat_Cliente1`
    FOREIGN KEY (`CLIENTE`)
    REFERENCES `grupo25`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Asistente1`
    FOREIGN KEY (`ASISTENTE`)
    REFERENCES `grupo25`.`ASISTENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Chat_Cliente1_idx` ON `grupo25`.`CHAT` (`CLIENTE` ASC) VISIBLE;

CREATE INDEX `fk_Chat_Asistente1_idx` ON `grupo25`.`CHAT` (`ASISTENTE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`MENSAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`MENSAJE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMISOR` INT NOT NULL,
  `CHAT` INT NOT NULL,
  `TEXTO` TEXT NOT NULL,
  `FECHA` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Mensaje_Persona1`
    FOREIGN KEY (`EMISOR`)
    REFERENCES `grupo25`.`PERSONA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Chat1`
    FOREIGN KEY (`CHAT`)
    REFERENCES `grupo25`.`CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mensaje_Persona1_idx` ON `grupo25`.`MENSAJE` (`EMISOR` ASC) VISIBLE;

CREATE INDEX `fk_Mensaje_Chat1_idx` ON `grupo25`.`MENSAJE` (`CHAT` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`ENTIDAD_BANCARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`ENTIDAD_BANCARIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `grupo25`.`ENTIDAD_BANCARIA` (`NOMBRE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `grupo25`.`CUENTA_EXTERNA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo25`.`CUENTA_EXTERNA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUENTA_BANCARIA` INT NOT NULL,
  `ENTIDAD_BANCARIA` INT NOT NULL,
  `SOSPECHOSA` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_CuentaExtranjera_EntidadBancaria1`
    FOREIGN KEY (`ENTIDAD_BANCARIA`)
    REFERENCES `grupo25`.`ENTIDAD_BANCARIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaExterna_CuentaBancaria1`
    FOREIGN KEY (`CUENTA_BANCARIA`)
    REFERENCES `grupo25`.`CUENTA_BANCARIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CuentaExtranjera_EntidadBancaria1_idx` ON `grupo25`.`CUENTA_EXTERNA` (`ENTIDAD_BANCARIA` ASC) VISIBLE;

CREATE INDEX `fk_CuentaExterna_CuentaBancaria1_idx` ON `grupo25`.`CUENTA_EXTERNA` (`CUENTA_BANCARIA` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
